# Generated by Django 4.2.23 on 2025-06-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_label", models.TextField(max_length=50)),
                (
                    "link_reference",
                    models.TextField(blank=True, max_length=50, null=True),
                ),
                ("link_sequence", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_home", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience_role", models.TextField(max_length=200)),
                ("experience_company_name", models.TextField(max_length=200)),
                ("experience_dates", models.TextField(max_length=200)),
                ("experience_description", models.TextField(max_length=4000)),
                ("experience_sequence", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
