# Generated by Django 4.2.23 on 2025-06-20 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_proficiency_section_specialization_skills_project_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
