# Generated by Django 4.2.23 on 2025-06-21 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_skills_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.TextField(max_length=200)),
                ("source_link", models.TextField(max_length=200)),
                (
                    "source_description",
                    models.TextField(blank=True, max_length=4000, null=True),
                ),
                ("source_sequence", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="proficiency",
            options={"verbose_name_plural": "proficiencies"},
        ),
        migrations.AddField(
            model_name="course",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="main.source",
            ),
        ),
        migrations.AddField(
            model_name="specialization",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specializations",
                to="main.source",
            ),
        ),
    ]
