# Generated by Django 4.2.23 on 2025-06-21 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_source_alter_proficiency_options_course_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="source_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="main.source",
            ),
        ),
    ]
