# Generated by Django 4.2.23 on 2025-06-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_source_source_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_link",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
