# Generated by Django 4.2.23 on 2025-06-21 00:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_source_source_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_description",
            field=tinymce.models.HTMLField(max_length=4000),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_description",
            field=tinymce.models.HTMLField(max_length=4000),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_description",
            field=tinymce.models.HTMLField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="specialization_description",
            field=tinymce.models.HTMLField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="experience_description",
            field=tinymce.models.HTMLField(max_length=4000),
        ),
    ]
