# Generated by Django 4.2.23 on 2025-06-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_course_course_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_description",
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_description",
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_description",
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="experience_description",
            field=models.TextField(max_length=4000),
        ),
    ]
