# Generated by Django 4.2.23 on 2025-06-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_course_course_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialization",
            name="specialization_description",
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
