# Generated by Django 4.2.23 on 2025-06-21 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_specialization_specialization_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_title", models.TextField(max_length=200)),
                ("page_slug", models.SlugField(max_length=200, unique=True)),
                ("page_content", models.TextField()),
                ("page_sequence", models.IntegerField(default=0)),
                ("page_is_active", models.BooleanField(default=True)),
                (
                    "page_navigation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="main.navigation",
                    ),
                ),
            ],
        ),
    ]
