# Generated by Django 4.2.23 on 2025-06-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technology_name", models.TextField(max_length=100)),
                ("technology_icon_class", models.TextField(max_length=100)),
                (
                    "technology_description",
                    models.TextField(blank=True, max_length=4000, null=True),
                ),
                ("technology_sequence", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
