# Generated by Django 4.2.23 on 2025-06-22 02:11

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_technology"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technology",
            options={"verbose_name_plural": "technologies"},
        ),
        migrations.RenameField(
            model_name="page",
            old_name="page_is_active",
            new_name="is_active",
        ),
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="page",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="page",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="proficiency",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="section",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="source",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="specialization",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="technology",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_description",
            field=tinymce.models.HTMLField(max_length=4000),
        ),
        migrations.AlterField(
            model_name="page",
            name="page_content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_description",
            field=tinymce.models.HTMLField(max_length=4000),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_description",
            field=tinymce.models.HTMLField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="specialization_description",
            field=tinymce.models.HTMLField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="technology_description",
            field=tinymce.models.HTMLField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="experience_description",
            field=tinymce.models.HTMLField(max_length=4000),
        ),
    ]
