# Generated by Django 4.2.23 on 2025-06-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_technology_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["sequence"]},
        ),
        migrations.AlterModelOptions(
            name="navigation",
            options={"ordering": ["sequence"]},
        ),
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["sequence"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["sequence"]},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["sequence"]},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["sequence"]},
        ),
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": ["sequence"]},
        ),
        migrations.AlterModelOptions(
            name="specialization",
            options={"ordering": ["sequence"]},
        ),
        migrations.AlterModelOptions(
            name="workexperience",
            options={"ordering": ["sequence"]},
        ),
        migrations.RenameField(
            model_name="course",
            old_name="course_sequence",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="page",
            old_name="page_sequence",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="proficiency",
            old_name="proficiency_sequence",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="project_sequence",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="section_sequence",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="skill",
            old_name="skill_sequence",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="source_sequence",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="specialization",
            old_name="specialization_sequence",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="technology",
            old_name="technology_sequence",
            new_name="sequence",
        ),
        migrations.RenameField(
            model_name="workexperience",
            old_name="experience_sequence",
            new_name="sequence",
        ),
        migrations.RemoveField(
            model_name="navigation",
            name="is_home",
        ),
        migrations.AddField(
            model_name="navigation",
            name="sequence",
            field=models.IntegerField(default=0),
        ),
    ]
