# Generated by Django 4.2.23 on 2025-06-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_course_options_alter_navigation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proficiency",
            options={"ordering": ["sequence"], "verbose_name_plural": "proficiencies"},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={},
        ),
        migrations.AlterModelOptions(
            name="technology",
            options={"ordering": ["sequence"], "verbose_name_plural": "technologies"},
        ),
        migrations.AlterModelOptions(
            name="workexperience",
            options={},
        ),
        migrations.RenameField(
            model_name="course",
            old_name="specialization",
            new_name="course_specialization",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="section",
            new_name="project_section",
        ),
        migrations.RenameField(
            model_name="specialization",
            old_name="section",
            new_name="specialization_section",
        ),
        migrations.RenameField(
            model_name="specialization",
            old_name="source",
            new_name="specialization_source",
        ),
        migrations.RemoveField(
            model_name="course",
            name="source",
        ),
        migrations.RemoveField(
            model_name="navigation",
            name="link_sequence",
        ),
    ]
