# Generated by Django 4.2.23 on 2025-06-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_proficiency_options_alter_section_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_skills",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="main.skill"
            ),
        ),
    ]
