# Generated by Django 4.2.23 on 2025-06-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_projectimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_github_link",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
