# Generated by Django 4.2.23 on 2025-06-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_project_project_github_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="experience_company_anon",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="experience_company_description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
