# Generated by Django 4.2.23 on 2025-06-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_workexperience_experience_company_anon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_show_github_link",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_show_link",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="experience_show_company_description",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="experience_show_company_name",
            field=models.BooleanField(default=False),
        ),
    ]
