# Generated by Django 4.2.23 on 2025-06-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_project_project_show_github_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workexperience",
            name="experience_company_description",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="experience_show_company_description",
        ),
    ]
