# Generated by Django 4.2.23 on 2025-06-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_remove_workexperience_experience_company_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="experience_skills",
            field=models.ManyToManyField(
                blank=True, related_name="workexperience", to="main.skill"
            ),
        ),
    ]
