# Generated by Django 4.2.23 on 2025-06-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_workexperience_experience_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="experience_context",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
